sudo: false
language: python
before_install:
- mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20150712/texlive.tar.xz
  | tar -JxC $HOME/texlive
install:
- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
- pip install Pygments
- tlmgr update --self
- tlmgr install babel-spanish
- export GIT_TAG=v`date +%Y-%m-%d-%H-%M-%S`
script:
- mkdir _build
- cd informe
- latexmk -pdf -shell-escape
- mv main.pdf ../_build/TIP-Aloi-MumukiGobstones-$GIT_TAG.pdf
- cd ..
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$GIT_CREDENTIALS@github.com/$TRAVIS_REPO_SLUG --tags
deploy:
  provider: releases
  api_key:
    secure: aUxgMwYQjDStMCXgrb0KE7tMukCFwAoLBoTkYYRTJMlKparN/coM8MC73DMEMSgsQRnLaeG1VG8Jrd46CKGjJhaG7dpNVjHFAVgjcVF4n5iQPoyoAAkn4swVM/xsGrixKFtQHqbkG4xPpPeQ9Q/L83Ru5v/TpEGfrJyrhxQRb1AR0hjID4gqpqtmseU6n7Yayt0iU/R1r54O9p5Q8hDSJEjtG0IBbP5twzRfTXke5Man6Vuvtd5QptzwwOb5u74IguU2FuNultRqjmrtENmNddVo/29oJ07fldRGcdq9QvSKT0fpuYPyuOApPJWSsJLuc5zJg2s1ah5R+fPx1Z3w/0Q0c/7c59PqOpt6MOrFLXLpqZB1KXK64DJlcJykbiFc2+Wf6yrCxun9PNdk8ruofXdDm44s0gdJHSu0cPWoLcIQ5UjcoewRaFlscU8Fv6yFtNiIUNBQ1KFxy4jj3Jf0Z5L/Wg0GlYteVz2RJBC7cVM3+3eXxB0tkpE7MPXLfBdb618dr5Fen1X68nxbyE8LAGdhXzM5V9gwyrCzbLjftjGTHQC1FqtM5no3aH/ye9547QJ/MbXQSRoEBS70s+g8J+h1x87Cet3iJEQSIs0eRSsL3Wk0vj5d9sgFOSKP0/tPy9x6Rm3PejfgI4bNWAPeZJi/T2hQUBkbeyBkxrRCnSI=
  skip_cleanup: true
  file: _build/TIP-Aloi-MumukiGobstones-$GIT_TAG.pdf
  on:
    repo: faloi/tip-mumuki-gobstones
    tags: false
env:
  global:
    secure: Fu5MWEEYmofd27+FSVFVAfnWI0V9RlkBbRGEF6s9bkozF9qZQ+pHHFYOhYULX7lz2A8paY9WMWEJdLSSNErR+xxwNPw+86FtQgXza0KAzbysidW2It03apc8bTc+ekypX/kzk1H+R1YdrFoLc2kztx3C9/bZOHeR73PD534jLVdt5GvtStwJxOFp9Ns87forp2OU5ZszOLfBDf8AXtXIrFO/+/VG/wP0n8s8Qo3UzXqQExWfkVBdxNBMfz/oeqRcCRKXbKgJPzyZLGhJ8nt72iXqZvLBiiQbfqkWajWrSJqhsJOrPHm0fGni1xqXT1BtlUgyn1hTRFIhdQTXkGMi/TnsKIDJ+vBmyr0T77Y6u1GgwCZN1J1jD4SM/PEPMRqZ1jskC1Ci4by++B/dAONR9IaSu63eJQtDMP4dJJYaXM11LGfWbDejUXfC70IhGOBumb5CVp332iVowpxl8wxa+AVYDeF5p6gULLrsQWs5LpqmB/0pHiXcEtE6rAUPqUj7Cr+6b7NT38iVStRkMy2ak/pHiuytigbWiOXQ4592dpwL+0nmh5o8+qbQTWZ03D6kdQEmK8galBM6cVtGfDsVhQdf1CRyH2nBzh2cXw8xEvQKZQSGdvaIHOWY8R8rIOjEW8NWmX+tg1Fvot1AQc6Oq6AUqFVWnE+P19sjYy+hwOQ=
branches:
  except:
    - /^v[0-9]/
